import LegalDocument from "@/components/legal/LegalDocument";

const sections = [
  { id: "acceptance", title: "Acceptance of Terms" },
  { id: "definitions", title: "Definitions" },
  { id: "services", title: "Description of Services" },
  { id: "registration", title: "Account Registration and Security" },
  { id: "payment-processing", title: "Payment Processing" },
  { id: "pci-compliance", title: "PCI DSS Compliance" },
  { id: "fees", title: "Fees and Payment" },
  { id: "prohibited-use", title: "Prohibited Use" },
  { id: "intellectual-property", title: "Intellectual Property Rights" },
  { id: "data-security", title: "Data Security and Privacy" },
  { id: "liability", title: "Limitation of Liability" },
  { id: "indemnification", title: "Indemnification" },
  { id: "termination", title: "Termination" },
  { id: "disputes", title: "Dispute Resolution" },
  { id: "changes", title: "Changes to Terms" },
  { id: "contact", title: "Contact Information" },
];

export default function TermsOfServicePage() {
  return (
    <LegalDocument
      title="Terms of Service"
      effectiveDate="December 15, 2025"
      lastUpdated="December 15, 2025"
      version="1.0.0"
      sections={sections}
    >
      <section id="acceptance" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          1. Acceptance of Terms
        </h2>
        <p className="mb-4">
          Welcome to Provvypay. By accessing or using our payment processing
          platform ("Service"), you agree to be bound by these Terms of Service
          ("Terms"). If you do not agree to these Terms, you may not use the
          Service.
        </p>
        <p className="mb-4">
          These Terms constitute a legally binding agreement between you
          (whether personally or on behalf of an entity) and Provvypay
          concerning your access to and use of the Service.
        </p>
      </section>

      <section id="definitions" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          2. Definitions
        </h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>"Merchant"</strong> means any business or individual that
            uses the Service to accept payments.
          </li>
          <li>
            <strong>"Customer"</strong> means any individual or entity that
            makes a payment through the Service.
          </li>
          <li>
            <strong>"Payment Link"</strong> means a unique URL generated by the
            Service to facilitate a payment transaction.
          </li>
          <li>
            <strong>"Organization"</strong> means the business entity registered
            to use the Service.
          </li>
          <li>
            <strong>"Platform"</strong> means the Provvypay payment processing
            system, including all associated software and services.
          </li>
        </ul>
      </section>

      <section id="services" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          3. Description of Services
        </h2>
        <p className="mb-4">
          Provvypay provides a payment processing platform that enables
          Merchants to:
        </p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>Create and manage payment links</li>
          <li>Accept payments via credit cards (through Stripe)</li>
          <li>
            Accept cryptocurrency payments (HBAR, USDC, USDT, AUDD via Hedera)
          </li>
          <li>Track and manage payment transactions</li>
          <li>Integrate with Xero accounting software</li>
          <li>Generate financial reports and analytics</li>
        </ul>
        <p>
          The Service acts as an intermediary between Merchants and third-party
          payment processors. Provvypay does not directly hold or process card
          information but facilitates secure payment processing through
          certified payment service providers.
        </p>
      </section>

      <section id="registration" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          4. Account Registration and Security
        </h2>
        <p className="mb-4">
          To use the Service, you must register for an account and provide
          accurate, complete, and current information. You are responsible for:
        </p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>Maintaining the confidentiality of your account credentials</li>
          <li>All activities that occur under your account</li>
          <li>Notifying us immediately of any unauthorized access</li>
          <li>Ensuring your account information remains accurate and current</li>
        </ul>
        <p>
          You must not share your account credentials with any third party. You
          are solely responsible for any loss or damage arising from your
          failure to maintain account security.
        </p>
      </section>

      <section id="payment-processing" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          5. Payment Processing
        </h2>
        
        <h3 className="text-xl font-semibold text-gray-900 mb-3 mt-6">
          5.1 Credit Card Payments
        </h3>
        <p className="mb-4">
          Credit card payments are processed through Stripe, a third-party
          payment processor. By using credit card payment features, you agree to
          Stripe's Terms of Service and Privacy Policy. Provvypay does not store
          credit card information on our servers.
        </p>

        <h3 className="text-xl font-semibold text-gray-900 mb-3 mt-6">
          5.2 Cryptocurrency Payments
        </h3>
        <p className="mb-4">
          Cryptocurrency payments are processed on the Hedera network. Merchants
          must provide a valid Hedera account ID to receive cryptocurrency
          payments. You acknowledge and agree that:
        </p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>Cryptocurrency transactions are irreversible once confirmed</li>
          <li>
            You are responsible for the security of your cryptocurrency wallets
          </li>
          <li>
            Exchange rate fluctuations may affect the final settlement amount
          </li>
          <li>Network fees apply to cryptocurrency transactions</li>
        </ul>

        <h3 className="text-xl font-semibold text-gray-900 mb-3 mt-6">
          5.3 Settlement
        </h3>
        <p>
          Payments are settled according to the terms of your agreement with the
          respective payment processor (Stripe for card payments, directly to
          your wallet for cryptocurrency payments). Provvypay is not responsible
          for delays in settlement by third-party processors.
        </p>
      </section>

      <section id="pci-compliance" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          6. PCI DSS Compliance
        </h2>
        <p className="mb-4">
          Provvypay is committed to maintaining Payment Card Industry Data
          Security Standard (PCI DSS) compliance. Our platform:
        </p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>
            Does not store, process, or transmit cardholder data on our servers
          </li>
          <li>
            Uses PCI DSS Level 1 certified payment processors (Stripe) for all
            card transactions
          </li>
          <li>
            Implements industry-standard security measures including encryption,
            access controls, and monitoring
          </li>
          <li>Regularly undergoes security audits and assessments</li>
        </ul>
        <p>
          Merchants using the Service benefit from Stripe's PCI DSS Level 1
          certification, the highest level of certification available in the
          payments industry.
        </p>
      </section>

      <section id="fees" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          7. Fees and Payment
        </h2>
        <p className="mb-4">
          Use of the Service may be subject to fees as communicated to you
          during registration or through your account dashboard. You agree to
          pay all applicable fees.
        </p>
        <p className="mb-4">
          Third-party payment processors (Stripe, Hedera network) charge their
          own fees, which are separate from any fees charged by Provvypay. You
          are responsible for understanding and paying all applicable
          third-party fees.
        </p>
        <p>
          We reserve the right to change our fee structure with 30 days' notice.
          Continued use of the Service after fee changes constitutes acceptance
          of the new fees.
        </p>
      </section>

      <section id="prohibited-use" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          8. Prohibited Use
        </h2>
        <p className="mb-4">You agree not to use the Service for:</p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>
            Illegal activities or products prohibited by law in your jurisdiction
          </li>
          <li>
            Fraudulent transactions or money laundering activities
          </li>
          <li>
            Adult content, gambling, or other high-risk merchant categories
            without prior approval
          </li>
          <li>Pyramid schemes, multi-level marketing, or ponzi schemes</li>
          <li>
            Sale of illegal drugs, weapons, or other prohibited items
          </li>
          <li>
            Unauthorized access to the Service or other users' accounts
          </li>
          <li>
            Circumventing security features or attempting to breach the platform
          </li>
          <li>
            Transmitting viruses, malware, or other harmful code
          </li>
        </ul>
        <p>
          We reserve the right to immediately suspend or terminate your account
          if we suspect prohibited use.
        </p>
      </section>

      <section id="intellectual-property" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          9. Intellectual Property Rights
        </h2>
        <p className="mb-4">
          The Service and all content, features, and functionality are owned by
          Provvypay and are protected by international copyright, trademark,
          patent, trade secret, and other intellectual property laws.
        </p>
        <p className="mb-4">
          You are granted a limited, non-exclusive, non-transferable license to
          access and use the Service for its intended purpose. You may not:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Copy, modify, or create derivative works of the Service</li>
          <li>Reverse engineer or attempt to extract source code</li>
          <li>Remove or modify any proprietary notices</li>
          <li>Use the Service to build a competing product</li>
        </ul>
      </section>

      <section id="data-security" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          10. Data Security and Privacy
        </h2>
        <p className="mb-4">
          Your use of the Service is subject to our Privacy Policy, which
          explains how we collect, use, and protect your information. By using
          the Service, you consent to our data practices as described in the
          Privacy Policy.
        </p>
        <p className="mb-4">We implement security measures including:</p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>Encryption of data in transit and at rest</li>
          <li>Regular security audits and vulnerability assessments</li>
          <li>Access controls and authentication mechanisms</li>
          <li>Monitoring and logging of system activities</li>
          <li>Incident response procedures</li>
        </ul>
        <p>
          While we take reasonable measures to protect your data, no system is
          completely secure. You acknowledge that you use the Service at your
          own risk.
        </p>
      </section>

      <section id="liability" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          11. Limitation of Liability
        </h2>
        <p className="mb-4">
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, PROVVYPAY SHALL NOT BE LIABLE
          FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE
          DAMAGES, INCLUDING WITHOUT LIMITATION:
        </p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>Loss of profits, revenue, data, or business opportunities</li>
          <li>Service interruptions or system failures</li>
          <li>Unauthorized access to your account or data</li>
          <li>
            Errors, mistakes, or inaccuracies in the Service
          </li>
          <li>Third-party payment processor failures or delays</li>
          <li>Cryptocurrency exchange rate fluctuations</li>
        </ul>
        <p className="mb-4">
          OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING FROM OR RELATED TO
          THE SERVICE SHALL NOT EXCEED THE GREATER OF: (A) THE AMOUNT YOU PAID
          TO US IN THE 12 MONTHS PRECEDING THE CLAIM, OR (B) $100 USD.
        </p>
        <p>
          The Service is provided "AS IS" and "AS AVAILABLE" without warranties
          of any kind, either express or implied.
        </p>
      </section>

      <section id="indemnification" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          12. Indemnification
        </h2>
        <p className="mb-4">
          You agree to indemnify, defend, and hold harmless Provvypay and its
          officers, directors, employees, and agents from any claims, damages,
          losses, liabilities, and expenses (including reasonable attorney fees)
          arising from:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Your use of the Service</li>
          <li>Your violation of these Terms</li>
          <li>Your violation of any rights of third parties</li>
          <li>Your transactions with Customers</li>
          <li>Disputes regarding products or services you sell</li>
        </ul>
      </section>

      <section id="termination" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          13. Termination
        </h2>
        <p className="mb-4">
          Either party may terminate this agreement at any time with notice. We
          may suspend or terminate your account immediately without notice if:
        </p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>You violate these Terms</li>
          <li>We suspect fraudulent activity</li>
          <li>Required by law or regulatory authorities</li>
          <li>We discontinue the Service</li>
        </ul>
        <p>
          Upon termination, your right to use the Service ceases immediately.
          Provisions that should survive termination (including indemnification,
          limitation of liability, and dispute resolution) will continue to
          apply.
        </p>
      </section>

      <section id="disputes" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          14. Dispute Resolution
        </h2>
        <p className="mb-4">
          Any disputes arising from or relating to these Terms or the Service
          shall be resolved through:
        </p>
        <ol className="list-decimal pl-6 space-y-2 mb-4">
          <li>
            <strong>Negotiation:</strong> The parties shall first attempt to
            resolve disputes through good-faith negotiation.
          </li>
          <li>
            <strong>Mediation:</strong> If negotiation fails, disputes shall be
            submitted to mediation.
          </li>
          <li>
            <strong>Arbitration:</strong> If mediation fails, disputes shall be
            resolved through binding arbitration in accordance with applicable
            arbitration rules.
          </li>
        </ol>
        <p>
          These Terms shall be governed by and construed in accordance with the
          laws of [Your Jurisdiction], without regard to conflict of law
          principles.
        </p>
      </section>

      <section id="changes" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          15. Changes to Terms
        </h2>
        <p className="mb-4">
          We reserve the right to modify these Terms at any time. We will
          provide notice of material changes by:
        </p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>Posting the updated Terms on our website</li>
          <li>Updating the "Last Updated" date</li>
          <li>Sending an email notification to your registered email address</li>
        </ul>
        <p>
          Your continued use of the Service after changes become effective
          constitutes acceptance of the modified Terms. If you do not agree to
          the changes, you must stop using the Service.
        </p>
      </section>

      <section id="contact" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          16. Contact Information
        </h2>
        <p className="mb-4">
          If you have questions about these Terms, please contact us:
        </p>
        <div className="bg-gray-50 p-6 rounded-lg">
          <p className="mb-2">
            <strong>Provvypay</strong>
          </p>
          <p className="mb-2">Email: legal@provvypay.com</p>
          <p className="mb-2">Email: support@provvypay.com</p>
          <p>Address: [Your Business Address]</p>
        </div>
      </section>

      <div className="mt-12 p-6 bg-blue-50 border border-blue-200 rounded-lg">
        <p className="text-sm text-blue-900">
          <strong>Important Notice:</strong> These Terms of Service constitute a
          legally binding agreement. Please read them carefully and consult with
          legal counsel if you have questions. By using the Service, you
          acknowledge that you have read, understood, and agree to be bound by
          these Terms.
        </p>
      </div>
    </LegalDocument>
  );
}







