/**
 * Live Anthropic extraction trace — no mocks.
 * Run from src/: npx tsx scripts/live-anthropic-extraction-trace.ts
 */
import Anthropic from '@anthropic-ai/sdk';
import { config } from 'dotenv';
import { resolve } from 'path';
import {
  buildExtractionSystemPrompt,
  buildExtractionUserPrompt,
} from '@/lib/ai-extractor/extraction-prompt';
import { validateExtractionResult } from '@/lib/ai-extractor/extraction-service';
import type { ExtractionResult } from '@/lib/ai-extractor/extraction-types';

config({ path: resolve(process.cwd(), '.env.local') });
config({ path: resolve(process.cwd(), '.env') });
config({ path: resolve(process.cwd(), '..', '.env.local') });
config({ path: resolve(process.cwd(), '..', '.env') });

const MODEL = process.env.EXTRACTOR_MODEL ?? 'claude-sonnet-4-6';

const CONVERSATIONS = {
  islandDjs: {
    label: 'Island DJs',
    text: `Venue:
Hi Sam, can you confirm your fee for Saturday Beach Event?

Island DJs:
Sure. Our fee is AUD 2,500 for the event.`,
  },
  coastal: {
    label: 'Coastal Promotions',
    text: `Coastal Promotions:
We'll receive 15% of net ticket sales generated by the event.`,
  },
};

function partyFieldReport(result: ExtractionResult, partyIndex = 0) {
  const p = result.parties[partyIndex];
  if (!p) {
    return { error: 'no party at index', partiesCount: result.parties.length };
  }
  return {
    name: { value: p.name.value, confidence: p.name.confidence },
    participationModel: {
      value: p.participationModel.value,
      confidence: p.participationModel.confidence,
    },
    fixedAmount: {
      value: p.fixedAmount.value,
      confidence: p.fixedAmount.confidence,
    },
    revenueSharePct: {
      value: p.revenueSharePct.value,
      confidence: p.revenueSharePct.confidence,
    },
    notes: { value: p.notes.value, confidence: p.notes.confidence },
    currency: {
      value: result.currency.value,
      confidence: result.currency.confidence,
    },
    overallConfidence: result.overallConfidence,
    uncertainties: result.uncertainties,
  };
}

async function traceOne(label: string, rawText: string) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    throw new Error('ANTHROPIC_API_KEY is not set — cannot run live extraction');
  }

  console.log('\n' + '='.repeat(80));
  console.log(label);
  console.log('='.repeat(80));
  console.log('\n--- INPUT CONVERSATION ---\n');
  console.log(rawText);

  const client = new Anthropic({ apiKey });
  const message = await client.messages.create({
    model: MODEL,
    max_tokens: 2048,
    temperature: 0,
    system: buildExtractionSystemPrompt(),
    messages: [{ role: 'user', content: buildExtractionUserPrompt(rawText) }],
  });

  const block = message.content[0];
  if (!block || block.type !== 'text') {
    console.log('\n--- RAW ANTHROPIC RESPONSE ---\n');
    console.log('(non-text block)', JSON.stringify(message.content));
    return;
  }

  const responseText = block.text.trim();

  console.log('\n--- 1. RAW ANTHROPIC RESPONSE TEXT ---\n');
  console.log(responseText);

  let parsed: unknown;
  let parseError: string | null = null;
  try {
    parsed = JSON.parse(responseText);
  } catch (e) {
    parseError = e instanceof Error ? e.message : String(e);
  }

  console.log('\n--- 2. PARSED JSON OBJECT ---\n');
  if (parseError) {
    console.log('JSON.parse FAILED:', parseError);
  } else {
    console.log(JSON.stringify(parsed, null, 2));
  }

  console.log('\n--- 3. VALIDATED ExtractionResult (production validateExtractionResult) ---\n');
  if (parseError) {
    console.log('(skipped — parse failed)');
    return;
  }

  try {
    const validated = validateExtractionResult(parsed);
    console.log(JSON.stringify(validated, null, 2));
    console.log('\n--- PARTY SUMMARY (before reviewFormFromExtraction) ---\n');
    console.log(JSON.stringify(partyFieldReport(validated), null, 2));
    return validated;
  } catch (validationErr) {
    console.log('Zod validation FAILED');
    if (validationErr && typeof validationErr === 'object' && 'issues' in validationErr) {
      console.log(JSON.stringify((validationErr as { issues: unknown[] }).issues, null, 2));
    } else {
      console.log(validationErr);
    }
  }
}

async function main() {
  console.log('Model:', MODEL);
  console.log('API key present:', Boolean(process.env.ANTHROPIC_API_KEY));

  await traceOne(CONVERSATIONS.islandDjs.label, CONVERSATIONS.islandDjs.text);
  await traceOne(CONVERSATIONS.coastal.label, CONVERSATIONS.coastal.text);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
