/**
 * Full pipeline trace for Island DJs + Coastal Promotions reproductions.
 * Run: npx tsx scripts/trace-conversation-compensation-pipeline.ts
 */
import { validateExtractionResult, extractAgreementFromText } from '@/lib/ai-extractor/extraction-service';
import { reviewFormFromExtraction } from '@/lib/ai-extractor/review-form-types';
import { mapSinglePartyToParticipant } from '@/lib/ai-extractor/extraction-mapper';
import type { ExtractionResult, ExtractedParty } from '@/lib/ai-extractor/extraction-types';
import type { RecentDeal } from '@/lib/data/mock-deal-network';
import type { DemoParticipant } from '@/components/deal-network-demo/invite-participant-modal';
import { hydrateParticipant } from '@/lib/operations/hydration/hydrate-participant';
import { hydrateOperationalParticipant } from '@/lib/operations/hydration/hydrate-operational-participant';
import { hasPersistedCompensationTerms } from '@/lib/operations/primitives/participant-earnings-primitives';
import { deriveCompensationState } from '@/lib/operations/derivations/derive-compensation-state';
import { repairScalarCompensationProfile } from '@/lib/participants/repair-scalar-compensation-profile';

function simulateDbPayload(participant: DemoParticipant): DemoParticipant {
  const data = JSON.parse(JSON.stringify(participant)) as DemoParticipant;
  return data;
}

function simulateReload(participant: DemoParticipant): DemoParticipant {
  const payload = simulateDbPayload(participant);
  const { participant: repaired } = repairScalarCompensationProfile({
    ...payload,
    id: payload.id ?? 'row-id',
    dealId: payload.dealId ?? 'deal-id',
    inviteToken: payload.inviteToken ?? 'token',
  });
  return repaired;
}

function field<T>(value: T, confidence: 'high' | 'medium' | 'low' | 'absent' = 'high') {
  return { value, confidence };
}

const CONVERSATIONS = {
  islandDjs: {
    label: 'Conversation 1 — Island DJs AUD 2500',
    text: `Venue:
Hi Sam, can you confirm your fee for Saturday Beach Event?

Island DJs:
Sure. Our fee is AUD 2,500 for the event.`,
    /** Shape when model follows prompt (fixed_payout + amount). */
    idealExtraction: (): ExtractionResult =>
      validateExtractionResult({
        projectName: field('Saturday Beach Event'),
        projectDescription: field(null),
        projectValue: field(2500),
        currency: field('AUD'),
        counterparty: field('Venue'),
        parties: [
          {
            id: 'ep-island-djs',
            name: field('Island DJs'),
            email: field(null, 'absent'),
            role: field('Contractor'),
            participationModel: field('fixed_payout'),
            fixedAmount: field(2500),
            revenueSharePct: field(null, 'absent'),
            notes: field('AUD 2,500 fee for the event'),
          },
        ],
        paymentTerms: [],
        uncertainties: [],
        overallConfidence: 'high',
        sourceHint: 'whatsapp',
        extractedAt: new Date().toISOString(),
      }),
    /** Common failure: amount only in notes, fixedAmount null. */
    failureExtractionMissingAmount: (): ExtractionResult =>
      validateExtractionResult({
        projectName: field('Saturday Beach Event'),
        projectDescription: field(null),
        projectValue: field(null, 'absent'),
        currency: field('AUD'),
        counterparty: field('Venue'),
        parties: [
          {
            id: 'ep-island-djs',
            name: field('Island DJs'),
            email: field(null, 'absent'),
            role: field('Performer'),
            participationModel: field('fixed_payout', 'medium'),
            fixedAmount: field(null, 'absent'),
            revenueSharePct: field(null, 'absent'),
            notes: field('AUD 2,500 for the event', 'high'),
          },
        ],
        paymentTerms: [],
        uncertainties: [],
        overallConfidence: 'medium',
        sourceHint: 'whatsapp',
        extractedAt: new Date().toISOString(),
      }),
  },
  coastal: {
    label: 'Conversation 2 — Coastal Promotions 15% net ticket sales',
    text: `Coastal Promotions:
We'll receive 15% of net ticket sales generated by the event.`,
    idealExtraction: (): ExtractionResult =>
      validateExtractionResult({
        projectName: field('Saturday Beach Event'),
        projectDescription: field(null),
        projectValue: field(null, 'absent'),
        currency: field('AUD'),
        counterparty: field(null, 'absent'),
        parties: [
          {
            id: 'ep-coastal',
            name: field('Coastal Promotions'),
            email: field(null, 'absent'),
            role: field('Referrer'),
            participationModel: field('revenue_share'),
            fixedAmount: field(null, 'absent'),
            revenueSharePct: field(15),
            notes: field('15% of net ticket sales'),
          },
        ],
        paymentTerms: [],
        uncertainties: [],
        overallConfidence: 'high',
        sourceHint: 'whatsapp',
        extractedAt: new Date().toISOString(),
      }),
    failureExtractionAttribution: (): ExtractionResult =>
      validateExtractionResult({
        projectName: field('Saturday Beach Event'),
        projectDescription: field(null),
        projectValue: field(null, 'absent'),
        currency: field('AUD'),
        counterparty: field(null, 'absent'),
        parties: [
          {
            id: 'ep-coastal',
            name: field('Coastal Promotions'),
            email: field(null, 'absent'),
            role: field('Promoter'),
            participationModel: field('customer_attribution'),
            fixedAmount: field(null, 'absent'),
            revenueSharePct: field(15),
            notes: field('15% of net ticket sales'),
          },
        ],
        paymentTerms: [],
        uncertainties: [],
        overallConfidence: 'high',
        sourceHint: 'whatsapp',
        extractedAt: new Date().toISOString(),
      }),
  },
};

function baseDeal(): RecentDeal {
  return {
    id: 'deal-saturday-beach',
    dealName: 'Saturday Beach Event',
    partner: 'Venue',
    value: 2500,
    introducer: '',
    closer: '',
    status: 'Pending',
    lastUpdated: new Date().toISOString(),
    paymentStatus: 'Not Paid',
    projectValueCurrency: 'AUD',
  };
}

type StageReport = {
  stage: string;
  file: string;
  line?: string;
  data: Record<string, unknown>;
};

function traceParty(
  label: string,
  result: ExtractionResult,
  expected: { type: string; amountOrPct: number }
): { stages: StageReport[]; firstDivergence: string | null } {
  const stages: StageReport[] = [];
  const original = result.parties[0]!;
  const party = original;

  stages.push({
    stage: '1_raw_extraction',
    file: 'extraction-service.ts (validateExtractionResult output)',
    data: {
      participationModel: party.participationModel.value,
      fixedAmount: party.fixedAmount.value,
      revenueSharePct: party.revenueSharePct.value,
      currency: result.currency.value,
      currencyConfidence: result.currency.confidence,
    },
  });

  const form = reviewFormFromExtraction(result, 'participant_add', 'whatsapp', undefined, {
    workspaceCurrency: 'AUD',
  });
  const reviewed = form.parties[0]!;

  stages.push({
    stage: '2_review_form',
    file: 'review-form-types.ts:reviewFormFromExtraction',
    line: '54-107',
    data: {
      participationModel: reviewed.participationModel,
      fixedAmount: reviewed.fixedAmount,
      revenueSharePct: reviewed.revenueSharePct,
      formCurrency: form.currency,
      extractedCurrencyUnsupported: form.extractedCurrencyUnsupported,
    },
  });

  stages.push({
    stage: '3_mapper_input',
    file: 'extraction-mapper.ts:mapSinglePartyToParticipant (ReviewedParty arg)',
    data: {
      participationModel: reviewed.participationModel,
      fixedAmount: reviewed.fixedAmount,
      revenueSharePct: reviewed.revenueSharePct,
    },
  });

  const mapped = mapSinglePartyToParticipant(reviewed, baseDeal(), '[AI Import]', original);

  stages.push({
    stage: '4_before_persist',
    file: 'extraction-mapper.ts:mapSinglePartyToParticipant return',
    line: '195-196',
    data: {
      participationModel: mapped.participationModel,
      commissionKind: mapped.commissionKind,
      commissionValue: mapped.commissionValue,
      compensationType: mapped.compensationProfile?.compensationType ?? null,
      profilePercentage: mapped.compensationProfile?.percentage ?? null,
      profileFixedAmount: mapped.compensationProfile?.fixedAmount ?? null,
      profileConfigured: mapped.compensationProfile?.configured ?? null,
    },
  });

  const dbPayload = simulateDbPayload(mapped);
  stages.push({
    stage: '5_db_payload',
    file: 'pilot-snapshot.server.ts:participant_payload (JSON round-trip)',
    data: {
      compensationType: dbPayload.compensationProfile?.compensationType ?? null,
      profilePercentage: dbPayload.compensationProfile?.percentage ?? null,
      profileFixedAmount: dbPayload.compensationProfile?.fixedAmount ?? null,
      profileConfigured: dbPayload.compensationProfile?.configured ?? null,
    },
  });

  const reloaded = simulateReload(dbPayload);
  const hydratedEntity = hydrateParticipant(reloaded)._entity;
  const hydratedOp = hydrateOperationalParticipant(reloaded);
  const compState = deriveCompensationState(hydratedEntity);

  stages.push({
    stage: '6_after_reload',
    file: 'getPilotSnapshotForUser + repairScalarCompensationProfile',
    data: {
      compensationType: reloaded.compensationProfile?.compensationType ?? null,
      profileConfigured: reloaded.compensationProfile?.configured ?? null,
    },
  });

  stages.push({
    stage: '7_hydrated_checks',
    file: 'participant-earnings-primitives + derive-compensation-state',
    data: {
      hasPersistedCompensationTerms: hasPersistedCompensationTerms(hydratedEntity),
      deriveCompensationState: {
        configured: compState.configured,
        type: compState.type,
        earningsPrimaryCompact: compState.earningsPrimaryCompact,
        settlementBasis: compState.settlementBasis,
      },
    },
  });

  let firstDivergence: string | null = null;
  const profile = mapped.compensationProfile;
  if (expected.type === 'FIXED_FEE') {
    if (profile?.compensationType !== 'FIXED_FEE' || profile.fixedAmount !== expected.amountOrPct) {
      firstDivergence = findFirstStage(stages, '4_before_persist', profile);
    }
  } else if (expected.type === 'REVENUE_SHARE') {
    if (
      profile?.compensationType !== 'REVENUE_SHARE' ||
      profile.percentage !== expected.amountOrPct
    ) {
      firstDivergence = findFirstStage(stages, '4_before_persist', profile);
    }
  }

  if (!firstDivergence && !hasPersistedCompensationTerms(hydratedEntity)) {
    firstDivergence = '7_hydrated_checks — hasPersistedCompensationTerms false';
  }

  return { stages, firstDivergence };
}

function findFirstStage(
  stages: StageReport[],
  fromStage: string,
  profile: DemoParticipant['compensationProfile']
): string {
  for (const s of stages) {
    if (s.stage >= fromStage || s.stage === fromStage) {
      return `${s.stage} @ ${s.file} — profile=${JSON.stringify(profile ?? null)}`;
    }
  }
  return `${fromStage} — profile missing or wrong`;
}

function printReport(label: string, report: ReturnType<typeof traceParty>) {
  console.log('\n' + '='.repeat(72));
  console.log(label);
  console.log('='.repeat(72));
  for (const s of report.stages) {
    console.log(`\n[${s.stage}] ${s.file}${s.line ? `:${s.line}` : ''}`);
    console.log(JSON.stringify(s.data, null, 2));
  }
  console.log('\nFIRST DIVERGENCE:', report.firstDivergence ?? 'none (matches expected through hydration)');
}

async function main() {
  const useLive = Boolean(process.env.ANTHROPIC_API_KEY);
  if (useLive) {
    console.log('--- LIVE AI EXTRACTION ---');
    for (const key of ['islandDjs', 'coastal'] as const) {
      const c = CONVERSATIONS[key];
      const live = await extractAgreementFromText(c.text);
      const party = live.parties[0];
      console.log(`\n${c.label} (live)`);
      console.log(
        JSON.stringify(
          {
            partiesCount: live.parties.length,
            participationModel: party?.participationModel.value,
            fixedAmount: party?.fixedAmount.value,
            revenueSharePct: party?.revenueSharePct.value,
            currency: live.currency.value,
            uncertainties: live.uncertainties,
          },
          null,
          2
        )
      );
      const expected =
        key === 'islandDjs'
          ? { type: 'FIXED_FEE', amountOrPct: 2500 }
          : { type: 'REVENUE_SHARE', amountOrPct: 15 };
      printReport(c.label + ' LIVE', traceParty(c.label, live, expected));
    }
  }

  console.log('\n\n--- IDEAL EXTRACTION SHAPES ---');
  printReport(
    CONVERSATIONS.islandDjs.label + ' IDEAL',
    traceParty(
      CONVERSATIONS.islandDjs.label,
      CONVERSATIONS.islandDjs.idealExtraction(),
      { type: 'FIXED_FEE', amountOrPct: 2500 }
    )
  );
  printReport(
    CONVERSATIONS.coastal.label + ' IDEAL',
    traceParty(
      CONVERSATIONS.coastal.label,
      CONVERSATIONS.coastal.idealExtraction(),
      { type: 'REVENUE_SHARE', amountOrPct: 15 }
    )
  );

  console.log('\n\n--- FAILURE SHAPES (production-like) ---');
  printReport(
    CONVERSATIONS.islandDjs.label + ' fixedAmount absent',
    traceParty(
      CONVERSATIONS.islandDjs.label,
      CONVERSATIONS.islandDjs.failureExtractionMissingAmount(),
      { type: 'FIXED_FEE', amountOrPct: 2500 }
    )
  );
  printReport(
    CONVERSATIONS.coastal.label + ' customer_attribution label',
    traceParty(
      CONVERSATIONS.coastal.label,
      CONVERSATIONS.coastal.failureExtractionAttribution(),
      { type: 'REVENUE_SHARE', amountOrPct: 15 }
    )
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
