/**
 * Instrument duplicate-resolution save branching (Entry Point B) against real pilot data.
 *
 * Requires: pilot tables, ANTHROPIC_API_KEY, DATABASE_URL (.env.local)
 * Optional: PILOT_TRACE_USER_ID, PILOT_TRACE_DEAL_ID, TRACE_PERSIST=1 (writes DB)
 *
 * Run from src/: npx tsx scripts/trace-duplicate-save-branch.ts
 */
import { config } from 'dotenv';
import { resolve } from 'path';
import Anthropic from '@anthropic-ai/sdk';
import { Prisma, PrismaClient } from '@prisma/client';
import {
  buildExtractionSystemPrompt,
  buildExtractionUserPrompt,
} from '@/lib/ai-extractor/extraction-prompt';
import { validateExtractionResult } from '@/lib/ai-extractor/extraction-service';
import { reviewFormFromExtraction } from '@/lib/ai-extractor/review-form-types';
import {
  detectDuplicates,
  defaultResolutions,
} from '@/lib/ai-extractor/duplicate-detection';
import {
  logDuplicateSavePathReport,
  runParticipantAddSaveBranchTrace,
  type DuplicateSavePathReport,
} from '@/lib/ai-extractor/duplicate-save-path-instrumentation';
import type { RecentDeal } from '@/lib/data/mock-deal-network';
import type { DemoParticipant } from '@/components/deal-network-demo/invite-participant-modal';
import { normParticipantName } from '@/lib/deal-network-demo/participant-merge';
import { normalizeParticipant } from '@/lib/operational/safe-operational-hydration';
import { EXTRACTOR_VERSION, SOURCE_TYPE_LABELS } from '@/lib/ai-extractor/extraction-types';
import type { ExtractionResult } from '@/lib/ai-extractor/extraction-types';

config({ path: resolve(process.cwd(), '.env.local') });
config({ path: resolve(process.cwd(), '.env') });

const MODEL = process.env.EXTRACTOR_MODEL ?? 'claude-sonnet-4-6';
const TRACE_PERSIST = process.env.TRACE_PERSIST === '1';

const CONVERSATIONS = [
  {
    label: 'Island DJs',
    text: `Venue:
Hi Sam, can you confirm your fee for Saturday Beach Event?

Island DJs:
Sure. Our fee is AUD 2,500 for the event.`,
    matchNames: ['island djs'],
  },
  {
    label: 'Coastal Promotions',
    text: `Coastal Promotions:
We'll receive 15% of net ticket sales generated by the event.`,
    matchNames: ['coastal promotions'],
  },
] as const;

function dealRowToRecentDeal(row: { id: string; deal_payload: Prisma.JsonValue }): RecentDeal {
  const payload = row.deal_payload as unknown as RecentDeal;
  return { ...payload, id: row.id };
}

function participantRowToDemo(row: {
  id: string;
  deal_id: string;
  invite_token: string;
  participant_payload: Prisma.JsonValue;
  approval_status?: string;
  approved_at?: Date | null;
}): DemoParticipant {
  const payload = row.participant_payload as unknown as DemoParticipant;
  const approvalStatus: DemoParticipant['approvalStatus'] =
    row.approval_status === 'Approved' || payload.approvalStatus === 'Approved'
      ? 'Approved'
      : 'Pending approval';
  return normalizeParticipant({
    ...payload,
    id: row.id,
    dealId: row.deal_id,
    inviteToken: row.invite_token,
    approvalStatus,
    approvedAt: row.approved_at ? row.approved_at.toISOString() : payload.approvedAt,
  });
}

async function liveExtract(text: string): Promise<ExtractionResult> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error('ANTHROPIC_API_KEY required');
  const client = new Anthropic({ apiKey });
  const message = await client.messages.create({
    model: MODEL,
    max_tokens: 2048,
    temperature: 0,
    system: buildExtractionSystemPrompt(),
    messages: [{ role: 'user', content: buildExtractionUserPrompt(text) }],
  });
  const block = message.content[0];
  if (!block || block.type !== 'text') throw new Error('non-text anthropic response');
  return validateExtractionResult(JSON.parse(block.text.trim()) as unknown);
}

function printHumanReport(report: DuplicateSavePathReport): void {
  const t = report.partyTraces[0];
  console.log('\n' + '='.repeat(72));
  console.log(report.label);
  console.log('='.repeat(72));
  console.log('\n1. duplicateMatches at save:');
  console.log(JSON.stringify(report.duplicateMatchesAtSave, null, 2));
  if (t) {
    console.log('\n2. form.duplicateResolutions immediately before save:');
    console.log(JSON.stringify(t.duplicateResolutionsBeforeSave, null, 2));
    console.log('\n3. resolution computed (party.id ?? "create"):');
    console.log(
      JSON.stringify(
        {
          partyId: t.partyId,
          resolutionRaw: t.resolutionRaw,
          resolutionComputed: t.resolutionComputed,
          expression: `form.duplicateResolutions["${t.partyId}"] ?? "create" → "${t.resolutionComputed}"`,
        },
        null,
        2
      )
    );
    console.log('\n4. save branch entered:');
    console.log(
      t.enteredBranch === 'update'
        ? '  → if (resolution === "update" && match)'
        : '  → else { updatedParticipants.push(built) }'
    );
    console.log(
      `  (matchFound=${t.matchFound}, existingId=${t.existingParticipantIdUpdated ?? 'n/a'}, builtId=${t.builtParticipantId})`
    );
  }
  console.log('\n5. participant count before save (full snapshot):', report.participantCountBeforeSave);
  console.log('6. participant count after save (full snapshot):', report.participantCountAfterSave);
  console.log('   on-deal before:', report.participantCountOnDealBefore, 'after:', report.participantCountOnDealAfter);
  console.log('\n7. same normalized name count on deal (before → after):');
  console.log(JSON.stringify({ before: report.sameNameCountBefore, after: report.sameNameCountAfter }, null, 2));
  console.log('\n8. snapshot diff:');
  console.log(JSON.stringify(report.snapshotDiff, null, 2));
}

async function assertPilotTables(prisma: PrismaClient): Promise<void> {
  const tables = await prisma.$queryRaw<{ table_name: string }[]>`
    SELECT table_name FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'deal_network_pilot_deals'`;
  if (tables.length === 0) {
    throw new Error(
      'deal_network_pilot_deals missing — deploy migrations on this DATABASE_URL, ensure Island DJs and Coastal Promotions exist on a project, then re-run.'
    );
  }
}

async function main() {
  const prisma = new PrismaClient();
  try {
    await assertPilotTables(prisma);

    const userId = process.env.PILOT_TRACE_USER_ID;
    const dealIdFilter = process.env.PILOT_TRACE_DEAL_ID;

    const deals = await prisma.deal_network_pilot_deals.findMany({
      where: userId ? { user_id: userId } : {},
      orderBy: { created_at: 'desc' },
      take: 30,
      include: { participants: true },
    });

    const targetDeal = deals.find((d) => {
      const names = d.participants.map((p) =>
        normParticipantName((p.participant_payload as DemoParticipant).name ?? '')
      );
      const hasIsland = names.some((n) => n.includes('island'));
      const hasCoastal = names.some((n) => n.includes('coastal'));
      return dealIdFilter
        ? d.id === dealIdFilter
        : hasIsland && hasCoastal;
    });

    if (!targetDeal) {
      const withAny = deals.filter((d) => d.participants.length > 0);
      throw new Error(
        `No deal with both Island DJs and Coastal Promotions participants. Deals with participants: ${withAny
          .map((d) => `${d.id} (${d.name}, n=${d.participants.length})`)
          .join('; ') || 'none'}. Set PILOT_TRACE_DEAL_ID or create participants first.`
      );
    }

    const deal = dealRowToRecentDeal(targetDeal);
    const projectParticipants = targetDeal.participants.map((row) =>
      participantRowToDemo({
        id: row.id,
        deal_id: row.deal_id,
        invite_token: row.invite_token,
        approval_status: row.approval_status,
        approved_at: row.approved_at,
        participant_payload: row.participant_payload,
      })
    );

    console.log('Target deal:', deal.id, deal.dealName, 'userId:', targetDeal.user_id);
    console.log(
      'Existing on project:',
      projectParticipants.map((p) => ({ id: p.id, name: p.name }))
    );

    const allRows = await prisma.deal_network_pilot_participants.findMany({
      where: { deal: { user_id: targetDeal.user_id } },
    });
    let snapshotParticipants = allRows.map((row) => participantRowToDemo(row));

    const provenanceTag = `[AI Import: ${SOURCE_TYPE_LABELS.whatsapp} · ${EXTRACTOR_VERSION}]`;

    for (const conv of CONVERSATIONS) {
      const extractionResult = await liveExtract(conv.text);
      const form = reviewFormFromExtraction(extractionResult, 'participant_add', 'whatsapp', deal.id, {
        project: deal,
        workspaceCurrency: 'AUD',
      });

      const matchesOnInit = detectDuplicates(form.parties, projectParticipants);
      form.duplicateResolutions = defaultResolutions(matchesOnInit);

      const reviewedParty = { ...form.parties[0]! };
      const existingRow = projectParticipants.find((p) =>
        conv.matchNames.some((mn) => normParticipantName(p.name) === mn)
      );
      if (existingRow && reviewedParty.name.trim().toLowerCase() !== existingRow.name.trim().toLowerCase()) {
        reviewedParty.name = existingRow.name;
      }
      form.parties = [reviewedParty];

      const duplicateMatchesAtSave = detectDuplicates(form.parties, projectParticipants);

      const { report, updatedParticipants } = runParticipantAddSaveBranchTrace({
        label: `save-branch:${conv.label}`,
        form,
        result: extractionResult,
        existingDeal: deal,
        duplicateMatchesAtSave,
        snapshotParticipants,
        provenanceTag,
      });

      logDuplicateSavePathReport(report);
      printHumanReport(report);

      snapshotParticipants = updatedParticipants;

      if (TRACE_PERSIST) {
        const { syncPilotSnapshotForUser } = await import(
          '@/lib/deal-network-demo/pilot-snapshot.server'
        );
        const snapshotDeals = (
          await prisma.deal_network_pilot_deals.findMany({
            where: { user_id: targetDeal.user_id },
          })
        ).map((r) => dealRowToRecentDeal(r));
        await syncPilotSnapshotForUser(targetDeal.user_id, snapshotDeals, snapshotParticipants);
        console.log(`\nPersisted after ${conv.label} import.`);
      }
    }

    if (!TRACE_PERSIST) {
      console.log('\nDry-run only (no DB write). Set TRACE_PERSIST=1 to persist each import.');
    }
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
