/**
 * Live compensation value trace: extraction → review form → mapper → persist round-trip.
 * Run from src/: npx tsx scripts/trace-compensation-pipeline-values.ts
 */
import { config } from 'dotenv';
import { resolve } from 'path';
import Anthropic from '@anthropic-ai/sdk';
import {
  buildExtractionSystemPrompt,
  buildExtractionUserPrompt,
} from '@/lib/ai-extractor/extraction-prompt';
import { validateExtractionResult } from '@/lib/ai-extractor/extraction-service';
import { reviewFormFromExtraction } from '@/lib/ai-extractor/review-form-types';
import { detectDuplicates, defaultResolutions } from '@/lib/ai-extractor/duplicate-detection';
import { runCompensationPipelineTraceForImport } from '@/lib/ai-extractor/compensation-pipeline-trace-runner';
import { EXTRACTOR_VERSION, SOURCE_TYPE_LABELS } from '@/lib/ai-extractor/extraction-types';
import type { RecentDeal } from '@/lib/data/mock-deal-network';
import type { DemoParticipant } from '@/components/deal-network-demo/invite-participant-modal';
import { DEFAULT_COMPENSATION_DRAFT } from '@/lib/participants/initialize-compensation-draft';

config({ path: resolve(process.cwd(), '.env.local') });
config({ path: resolve(process.cwd(), '.env') });

const MODEL = process.env.EXTRACTOR_MODEL ?? 'claude-sonnet-4-6';

const CONVERSATIONS = [
  {
    label: 'Island DJs',
    text: `Venue:
Hi Sam, can you confirm your fee for Saturday Beach Event?

Island DJs:
Sure. Our fee is AUD 2,500 for the event.`,
    expectations: { fixedAmount: 2500, compensationType: 'FIXED_FEE', configured: true },
  },
  {
    label: 'Coastal Promotions',
    text: `Coastal Promotions:
We'll receive 15% of net ticket sales generated by the event.`,
    expectations: { revenueSharePct: 15, compensationType: 'REVENUE_SHARE', configured: true },
  },
] as const;

function baseDeal(id: string): RecentDeal {
  return {
    id,
    dealName: 'Pipeline Trace Project',
    partner: 'Venue',
    value: 10000,
    introducer: '',
    closer: '',
    status: 'Pending',
    lastUpdated: new Date().toISOString(),
    paymentStatus: 'Not Paid',
    projectValueCurrency: 'AUD',
  };
}

function existingWithDraftProfile(id: string, name: string, model: DemoParticipant['participationModel']): DemoParticipant {
  return {
    id,
    name,
    email: '',
    role: 'Contributor',
    commissionKind: model === 'fixed_payout' ? 'fixed_amount' : 'pct_deal_value',
    commissionValue: 0,
    status: 'Pending',
    approvalStatus: 'Pending approval',
    inviteToken: `tok-${id}`,
    dealId: 'deal-trace',
    agreementLifecycle: 'NOT_CREATED',
    participantLifecycle: 'DRAFT',
    participationModel: model,
    compensationProfile: { ...DEFAULT_COMPENSATION_DRAFT },
  };
}

function field<T>(value: T, confidence: 'high' | 'medium' | 'low' | 'absent' = 'high') {
  return { value, confidence };
}

/** Cached live extraction (2026-06-03 run) — used for corruption repro without second API call. */
function cachedExtraction(label: string) {
  if (label === 'Island DJs') {
    return validateExtractionResult({
      projectName: field('Saturday Beach Event'),
      projectDescription: field(null, 'absent'),
      projectValue: field(2500),
      currency: field('AUD'),
      counterparty: field('Venue', 'medium'),
      parties: [
        {
          id: 'ep-1',
          name: field('Island DJs'),
          email: field(null, 'absent'),
          role: field('Contractor'),
          participationModel: field('fixed_payout'),
          fixedAmount: field(2500),
          revenueSharePct: field(null, 'absent'),
          notes: field(''),
        },
      ],
      paymentTerms: [],
      uncertainties: [],
      overallConfidence: 'high',
      sourceHint: 'whatsapp',
      extractedAt: new Date().toISOString(),
    });
  }
  return validateExtractionResult({
    projectName: field(null, 'absent'),
    projectDescription: field('Event with ticket sales', 'medium'),
    projectValue: field(null, 'absent'),
    currency: field(null, 'absent'),
    counterparty: field(null, 'absent'),
    parties: [
      {
        id: 'ep-1',
        name: field('Coastal Promotions'),
        email: field(null, 'absent'),
        role: field('Partner', 'medium'),
        participationModel: field('revenue_share'),
        fixedAmount: field(null, 'absent'),
        revenueSharePct: field(15),
        notes: field('15% of net ticket sales'),
      },
    ],
    paymentTerms: [],
    uncertainties: [],
    overallConfidence: 'low',
    sourceHint: null,
    extractedAt: new Date().toISOString(),
  });
}

async function liveExtract(text: string) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error('ANTHROPIC_API_KEY required');
  const client = new Anthropic({ apiKey });
  const message = await client.messages.create({
    model: MODEL,
    max_tokens: 2048,
    temperature: 0,
    system: buildExtractionSystemPrompt(),
    messages: [{ role: 'user', content: buildExtractionUserPrompt(text) }],
  });
  const block = message.content[0];
  if (!block || block.type !== 'text') throw new Error('non-text anthropic response');
  return validateExtractionResult(JSON.parse(block.text.trim()) as unknown);
}

function printSnapshots(label: string, snapshots: ReturnType<typeof runCompensationPipelineTraceForImport>['snapshots']) {
  console.log('\n' + '='.repeat(72));
  console.log(label);
  console.log('='.repeat(72));
  for (const s of snapshots) {
    console.log(JSON.stringify(s, null, 2));
  }
}

const deal = baseDeal('deal-trace');
const provenanceTag = `[AI Import: ${SOURCE_TYPE_LABELS.whatsapp} · ${EXTRACTOR_VERSION}]`;

async function runTrace(
  conv: (typeof CONVERSATIONS)[number],
  options?: { nullifyAmounts?: boolean; labelSuffix?: string; skipLiveExtract?: boolean }
) {
  const result = options?.skipLiveExtract
    ? cachedExtraction(conv.label)
    : await liveExtract(conv.text);
  const form = reviewFormFromExtraction(result, 'participant_add', 'whatsapp', deal.id, {
    project: deal,
    workspaceCurrency: 'AUD',
  });
  let party = form.parties[0]!;
  if (options?.nullifyAmounts) {
    party = {
      ...party,
      fixedAmount: conv.label === 'Island DJs' ? null : party.fixedAmount,
      revenueSharePct: conv.label === 'Coastal Promotions' ? null : party.revenueSharePct,
    };
  }
  const model = party.participationModel === 'fixed_payout' ? 'fixed_payout' : 'revenue_share';
  const existing = existingWithDraftProfile(
    `existing-${party.name.replace(/\s+/g, '-').toLowerCase()}`,
    party.name,
    model
  );
  const projectParticipants = [existing];
  const matches = detectDuplicates(form.parties, projectParticipants);
  form.duplicateResolutions = defaultResolutions(matches);

  const traceLabel = `${conv.label}${options?.labelSuffix ?? ''}`;
  const { snapshots } = runCompensationPipelineTraceForImport({
    label: traceLabel,
    result,
    formAtSave: form,
    party,
    project: deal,
    provenanceTag,
    entryPoint: 'participant_add',
    sourceType: 'whatsapp',
    currencyContext: { project: deal, workspaceCurrency: 'AUD' },
    existingParticipantsForDuplicate: projectParticipants,
    mergeExistingParticipant:
      matches.length > 0 && form.duplicateResolutions[party.id] === 'update'
        ? existing
        : null,
  });

  return { snapshots, traceLabel };
}

function printStageTable(snapshots: ReturnType<typeof runCompensationPipelineTraceForImport>['snapshots']) {
  console.log('\n| stage | participationModel | fixedAmount | revenueSharePct | compensationType | configured |');
  console.log('|-------|-------------------|-------------|---------------|------------------|------------|');
  for (const s of snapshots) {
    console.log(
      `| ${s.stage} | ${s.participationModel ?? '—'} | ${s.fixedAmount ?? s.compensationProfile?.fixedAmount ?? '—'} | ${s.revenueSharePct ?? s.compensationProfile?.percentage ?? '—'} | ${s.compensationType ?? '—'} | ${s.configured ?? '—'} |`
    );
  }
}

async function main() {
  const mode = process.env.TRACE_MODE ?? 'live';
  if (mode === 'live' || mode === 'all') {
    console.log('\n### LIVE IMPORT (real Anthropic + update merge, form at save) ###');
    for (const conv of CONVERSATIONS) {
      const { snapshots } = await runTrace(conv);
      printStageTable(snapshots);
    }
  }
  if (mode === 'corruption' || mode === 'all') {
    console.log('\n### MATCHES OBSERVED DB (amounts absent at save + merge w/ draft profile) ###');
    for (const conv of CONVERSATIONS) {
      const { snapshots } = await runTrace(conv, {
        nullifyAmounts: true,
        labelSuffix: ':observedDbShape',
        skipLiveExtract: true,
      });
      printStageTable(snapshots);
    }
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
