import type {
  PaymentIntelligenceItem,
  PaymentRailWatchItem,
} from '@/lib/journey/payment-intelligence-types';

/**
 * Curated payment-infrastructure developments from public sources.
 * This is a catalog snapshot — not live network data, live pricing,
 * availability, or transaction volumes.
 */
export const PAYMENT_INTELLIGENCE_FEED: PaymentIntelligenceItem[] = [
  {
    id: 'rba-psr-review-2026-06',
    publishedAt: '2026-06-25',
    source: 'Reserve Bank of Australia',
    sourceUrl: 'https://www.rba.gov.au/media-releases/2026/mr-26-17.html',
    sourceType: 'central_bank',
    provider: 'RBA',
    rails: ['rba', 'npp', 'bank', 'visa', 'mastercard'],
    countries: ['AU'],
    corridors: ['cross_border'],
    topic: 'regulation',
    headline: 'Australia is reviewing how payment systems are regulated.',
    summary:
      "The RBA's Review of Payments System Regulation asks which issues to prioritise: merchant choice of methods and providers, account-to-account competition with cards, mobile wallets, and safety.",
    businessImpact:
      'This could change which payment methods become more competitive in Australia and how businesses choose between bank transfer, cards and newer rails.',
    relevance: ['Australia', 'A2A', 'Bank transfers', 'Cards'],
    confidence: 'catalog',
    freshness: 'catalog_snapshot',
    status: 'changing',
    signal: 'regulatory_uncertainty',
    pulseLabel: 'Australian payment-system regulation under review',
  },
  {
    id: 'rba-a2a-vision-2026-07',
    publishedAt: '2026-07-08',
    source: 'Reserve Bank of Australia',
    sourceUrl: 'https://www.rba.gov.au/media-releases/2026/mr-26-18.html',
    sourceType: 'central_bank',
    provider: 'RBA',
    rails: ['npp', 'bank', 'rba'],
    countries: ['AU'],
    corridors: ['cross_border'],
    topic: 'instant_payment',
    headline: 'Australia published a shared vision for account-to-account payments.',
    summary:
      'The A2A Payments Roundtable released a national vision for secure, available and competitive account-to-account payments. An industry roadmap is the next step.',
    businessImpact:
      'Domestic bank-transfer and instant-payment options may become richer and more competitive as the roadmap is defined — relevant when an Australian business pays locally or funds a cross-border transfer.',
    relevance: ['Australia', 'A2A', 'NPP', 'Bank transfers'],
    confidence: 'catalog',
    freshness: 'catalog_snapshot',
    status: 'changing',
    signal: 'regulatory_momentum',
    pulseLabel: 'A2A payments vision published · roadmap next',
  },
  {
    id: 'swift-retail-framework-2026-03',
    publishedAt: '2026-03-05',
    source: 'SWIFT',
    sourceUrl:
      'https://www.swift.com/news-events/news/transforming-consumer-payments-banks-roll-out-new-framework-retail-transactions',
    sourceType: 'payment_network',
    provider: 'SWIFT',
    rails: ['swift', 'bank'],
    countries: ['AU', 'GB', 'US', 'IN', 'TH', 'DE', 'CA'],
    corridors: ['cross_border'],
    topic: 'correspondent_banking',
    headline: 'SWIFT is expanding its cross-border retail payment framework.',
    summary:
      'More than 50 banks signed up to a framework aimed at predictable cost, full-value delivery, faster speeds and end-to-end traceability. An initial group committed to processing payments on corridors including Australia by June 2026.',
    businessImpact:
      'Traditional bank transfers may become more competitive on speed and transparency in participating corridors — including routes that touch Australia.',
    relevance: ['Cross-border', 'Banks', 'SWIFT'],
    confidence: 'catalog',
    freshness: 'catalog_snapshot',
    status: 'changing',
    signal: 'corridor_expansion',
    pulseLabel: 'Cross-border retail framework expanding',
  },
  {
    id: 'bis-agora-rvt-2026-07',
    publishedAt: '2026-07-01',
    source: 'Bank for International Settlements',
    sourceUrl: 'https://www.bis.org/about/bisih/topics/fmis/agora/rvt.htm',
    sourceType: 'industry_body',
    provider: 'BIS',
    rails: ['digital_dollar', 'bank'],
    countries: ['US', 'GB', 'DE', 'JP'],
    corridors: ['cross_border'],
    topic: 'digital_dollar',
    headline: 'Wholesale digital-settlement tests moved to real-value transactions.',
    summary:
      'Project Agorá completed real-value testing in July 2026: 28 institutions settled tokenised reserves and deposits on a shared multi-currency platform. This is a prototype, not a public retail rail.',
    businessImpact:
      'Institutional digital-settlement options are being tested. They are not a live quote or a confirmed supplier payout path, but they signal that alternative settlement rails may matter later.',
    relevance: ['Digital settlement', 'Cross-border', 'Wholesale'],
    confidence: 'catalog',
    freshness: 'catalog_snapshot',
    status: 'emerging',
    signal: 'provider_adoption',
    pulseLabel: 'Institutional settlement tests progressing',
  },
];

export const PAYMENT_INTELLIGENCE_SNAPSHOT_DATE = PAYMENT_INTELLIGENCE_FEED.reduce(
  (latest, item) => (item.publishedAt > latest ? item.publishedAt : latest),
  PAYMENT_INTELLIGENCE_FEED[0]?.publishedAt ?? '2026-07-08'
);

export const PAYMENT_RAIL_WATCHLIST: PaymentRailWatchItem[] = [
  {
    id: 'swift',
    rank: 1,
    name: 'SWIFT',
    category: 'Bank transfer',
    lens: 'Cross-border infrastructure',
    reason:
      'A retail framework is changing the economics and predictability of international transfers on participating corridors.',
    status: 'changing',
    movement: 'up',
    movementReason: 'Retail payments framework rolling out in 2026.',
    scopes: ['all', 'australia', 'asia_pacific', 'cross_border', 'business'],
  },
  {
    id: 'wise',
    rank: 2,
    name: 'Wise',
    category: 'International transfer',
    lens: 'Cost / FX',
    reason: 'Pricing and corridor availability remain important for SME cross-border payments.',
    status: 'active',
    movement: 'steady',
    movementReason: null,
    scopes: ['all', 'australia', 'asia_pacific', 'cross_border', 'business'],
  },
  {
    id: 'airwallex',
    rank: 3,
    name: 'Airwallex',
    category: 'Business payments',
    lens: 'Business infrastructure',
    reason: 'Strong relevance for businesses managing multiple currencies and suppliers.',
    status: 'active',
    movement: 'up',
    movementReason: 'Business multi-currency payouts remain a watched alternative to correspondent banking.',
    scopes: ['all', 'australia', 'asia_pacific', 'cross_border', 'business'],
  },
  {
    id: 'npp',
    rank: 4,
    name: 'NPP / A2A',
    category: 'Instant payment',
    lens: 'Domestic rail choice',
    reason:
      'Australia’s account-to-account vision and regulation review could change how domestic transfers compete with cards.',
    status: 'changing',
    movement: 'up',
    movementReason: 'A2A vision published; regulatory review underway.',
    scopes: ['all', 'australia', 'business'],
  },
  {
    id: 'visa',
    rank: 5,
    name: 'Visa',
    category: 'Card network',
    lens: 'Acceptance / collections',
    reason: 'Still the default collection rail when the other party needs to pay from a card or wallet.',
    status: 'watching',
    movement: 'steady',
    movementReason: null,
    scopes: ['all', 'australia', 'cross_border', 'business'],
  },
  {
    id: 'mastercard',
    rank: 6,
    name: 'Mastercard',
    category: 'Card network',
    lens: 'Acceptance / collections',
    reason: 'Card-network competition and merchant choice are explicitly in the RBA review.',
    status: 'watching',
    movement: 'down',
    movementReason: 'Regulatory attention on card vs A2A competition in Australia.',
    scopes: ['all', 'australia', 'cross_border', 'business'],
  },
  {
    id: 'digital_dollar',
    rank: 7,
    name: 'Digital-dollar',
    category: 'Digital settlement',
    lens: 'Settlement alternatives',
    reason:
      'Institutional tests are progressing. Compatible accounts are still required, and this is not a live retail quote.',
    status: 'emerging',
    movement: 'up',
    movementReason: 'Wholesale real-value settlement tests in 2026.',
    scopes: ['all', 'asia_pacific', 'cross_border'],
  },
  {
    id: 'stripe',
    rank: 8,
    name: 'Stripe',
    category: 'Payment link',
    lens: 'Collections',
    reason: 'Useful when the other party should pay without sharing bank details — usually at higher acceptance cost.',
    status: 'active',
    movement: 'steady',
    movementReason: null,
    scopes: ['all', 'business', 'cross_border'],
  },
  {
    id: 'ofx',
    rank: 9,
    name: 'OFX',
    category: 'FX transfer',
    lens: 'FX',
    reason: 'Specialist FX remains a watched option for larger or recurring cross-border payouts.',
    status: 'watching',
    movement: 'steady',
    movementReason: null,
    scopes: ['all', 'australia', 'cross_border', 'business'],
  },
  {
    id: 'paypal',
    rank: 10,
    name: 'PayPal',
    category: 'Digital wallet',
    lens: 'Familiar checkout',
    reason: 'Still a low-friction way for some counterparties to pay, with typical wallet and FX tradeoffs.',
    status: 'watching',
    movement: 'steady',
    movementReason: null,
    scopes: ['all', 'business', 'cross_border'],
  },
];
