import LegalDocument from '@/components/legal/LegalDocument';

const sections = [
  { id: 'introduction', title: 'Introduction' },
  { id: 'information-we-collect', title: 'Information We Collect' },
  { id: 'how-we-use-information', title: 'How We Use Information' },
  { id: 'ai-processing', title: 'AI Processing' },
  { id: 'disclosure-of-information', title: 'Disclosure of Information' },
  { id: 'data-storage', title: 'Data Storage' },
  { id: 'international-transfers', title: 'International Transfers' },
  { id: 'cookies', title: 'Cookies' },
  { id: 'marketing-communications', title: 'Marketing Communications' },
  { id: 'access-and-correction', title: 'Access and Correction' },
  { id: 'data-retention', title: 'Data Retention' },
  { id: 'childrens-privacy', title: "Children's Privacy" },
  { id: 'changes-to-policy', title: 'Changes to this Policy' },
  { id: 'contact', title: 'Contact' },
];

export function ProvvypayPrivacyDocument() {
  return (
    <LegalDocument
      title="Privacy Policy"
      effectiveDate="8 June 2026"
      lastUpdated="8 June 2026"
      version="2.0.0"
      sections={sections}
    >
      <section id="introduction" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Introduction</h2>
        <p className="mb-4">
          Provvypay (&quot;we&quot;, &quot;our&quot;, &quot;us&quot;) respects your privacy and is
          committed to protecting personal information.
        </p>
        <p>
          This Privacy Policy explains how we collect, use, disclose and safeguard information when
          you use our website and services.
        </p>
      </section>

      <section id="information-we-collect" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Information We Collect</h2>
        <p className="mb-4">We may collect:</p>

        <h3 className="text-xl font-semibold text-gray-900 mb-3">Account Information</h3>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>name</li>
          <li>email address</li>
          <li>phone number</li>
          <li>organisation name</li>
          <li>account credentials</li>
        </ul>

        <h3 className="text-xl font-semibold text-gray-900 mb-3">Business Information</h3>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>uploaded agreements</li>
          <li>conversations</li>
          <li>documents</li>
          <li>invoices</li>
          <li>settlement information</li>
          <li>participant details</li>
        </ul>

        <h3 className="text-xl font-semibold text-gray-900 mb-3">Technical Information</h3>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>IP address</li>
          <li>browser type</li>
          <li>operating system</li>
          <li>device information</li>
          <li>usage analytics</li>
        </ul>

        <h3 className="text-xl font-semibold text-gray-900 mb-3">Integration Information</h3>
        <p>
          Where you connect third-party services, we may access information necessary to provide
          integrations.
        </p>
      </section>

      <section id="how-we-use-information" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">3. How We Use Information</h2>
        <p className="mb-4">We use information to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>provide Services;</li>
          <li>create and manage accounts;</li>
          <li>process uploaded content;</li>
          <li>generate agreement intelligence;</li>
          <li>improve platform performance;</li>
          <li>provide support;</li>
          <li>maintain security;</li>
          <li>communicate updates;</li>
          <li>comply with legal obligations.</li>
        </ul>
      </section>

      <section id="ai-processing" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">4. AI Processing</h2>
        <p className="mb-4">
          Uploaded content may be processed using artificial intelligence technologies.
        </p>
        <p className="mb-4">This processing may be used to:</p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>identify agreements;</li>
          <li>extract obligations;</li>
          <li>identify participants;</li>
          <li>generate workflow recommendations;</li>
          <li>create reports and summaries.</li>
        </ul>
        <p>Users remain responsible for validating outputs generated by AI systems.</p>
      </section>

      <section id="disclosure-of-information" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Disclosure of Information</h2>
        <p className="mb-4">We may disclose information to:</p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>cloud infrastructure providers;</li>
          <li>analytics providers;</li>
          <li>customer support providers;</li>
          <li>payment providers;</li>
          <li>accounting integration providers;</li>
          <li>professional advisers;</li>
          <li>regulators and law enforcement where required by law.</li>
        </ul>
        <p>We do not sell personal information.</p>
      </section>

      <section id="data-storage" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Data Storage</h2>
        <p className="mb-4">
          Information may be stored on secure cloud infrastructure operated by trusted service
          providers.
        </p>
        <p className="mb-4">
          We implement reasonable administrative, technical and organisational safeguards designed
          to protect information.
        </p>
        <p>No internet transmission or storage system is completely secure.</p>
      </section>

      <section id="international-transfers" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">7. International Transfers</h2>
        <p className="mb-4">
          Information may be processed in Australia or other countries where our service providers
          operate.
        </p>
        <p>By using the Services, you consent to such transfers where permitted by law.</p>
      </section>

      <section id="cookies" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">8. Cookies</h2>
        <p className="mb-4">We may use cookies and similar technologies to:</p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>authenticate users;</li>
          <li>improve performance;</li>
          <li>analyse website usage;</li>
          <li>remember preferences.</li>
        </ul>
        <p>Users can manage cookie settings through their browser.</p>
      </section>

      <section id="marketing-communications" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">9. Marketing Communications</h2>
        <p className="mb-4">We may send:</p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li>service notifications;</li>
          <li>product updates;</li>
          <li>newsletters;</li>
          <li>educational content.</li>
        </ul>
        <p>Users may unsubscribe from marketing communications at any time.</p>
      </section>

      <section id="access-and-correction" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">10. Access and Correction</h2>
        <p className="mb-4">
          You may request access to personal information we hold about you and request corrections
          where information is inaccurate.
        </p>
        <p>
          Requests may be submitted to{' '}
          <a href="mailto:support@provvypay.com" className="text-blue-600 hover:underline">
            support@provvypay.com
          </a>
          .
        </p>
      </section>

      <section id="data-retention" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">11. Data Retention</h2>
        <p className="mb-4">We retain information only for as long as reasonably necessary to:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>provide Services;</li>
          <li>comply with legal obligations;</li>
          <li>resolve disputes;</li>
          <li>enforce agreements.</li>
        </ul>
      </section>

      <section id="childrens-privacy" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">12. Children&apos;s Privacy</h2>
        <p>The Services are not intended for individuals under 18 years of age.</p>
      </section>

      <section id="changes-to-policy" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">13. Changes to this Policy</h2>
        <p className="mb-4">We may update this Privacy Policy from time to time.</p>
        <p className="mb-4">Updated versions will be published on our website.</p>
        <p>
          Continued use of the Services after publication constitutes acceptance of the updated
          policy.
        </p>
      </section>

      <section id="contact" className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">14. Contact</h2>
        <p className="mb-2 font-semibold">Provvypay</p>
        <p>
          Email:{' '}
          <a href="mailto:hello@provvypay.com" className="text-blue-600 hover:underline">
            hello@provvypay.com
          </a>
        </p>
        <p className="mt-2">For privacy-related enquiries, please contact us using the details above.</p>
      </section>
    </LegalDocument>
  );
}
