/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SystemRouteImport } from './routes/system'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as AssessmentIndexRouteImport } from './routes/assessment.index'
import { Route as WorkspaceWorkflowsRouteImport } from './routes/workspace.workflows'
import { Route as WorkspaceTimelineRouteImport } from './routes/workspace.timeline'
import { Route as WorkspaceSettingsRouteImport } from './routes/workspace.settings'
import { Route as WorkspaceConnectedRouteImport } from './routes/workspace.connected'
import { Route as WorkspaceAdvisorRouteImport } from './routes/workspace.advisor'
import { Route as AssessmentRecommendationRouteImport } from './routes/assessment.recommendation'
import { Route as AssessmentProvisioningRouteImport } from './routes/assessment.provisioning'
import { Route as AssessmentCreateWorkspaceRouteImport } from './routes/assessment.create-workspace'
import { Route as AssessmentConnectRouteImport } from './routes/assessment.connect'
import { Route as AssessmentBusinessRouteImport } from './routes/assessment.business'
import { Route as AssessmentAnalysisRouteImport } from './routes/assessment.analysis'
import { Route as WorkspaceWorkflowReconciliationRouteImport } from './routes/workspace.workflow.reconciliation'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const AssessmentIndexRoute = AssessmentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssessmentRoute,
} as any)
const WorkspaceWorkflowsRoute = WorkspaceWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceTimelineRoute = WorkspaceTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceConnectedRoute = WorkspaceConnectedRouteImport.update({
  id: '/connected',
  path: '/connected',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAdvisorRoute = WorkspaceAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => WorkspaceRoute,
} as any)
const AssessmentRecommendationRoute =
  AssessmentRecommendationRouteImport.update({
    id: '/recommendation',
    path: '/recommendation',
    getParentRoute: () => AssessmentRoute,
  } as any)
const AssessmentProvisioningRoute = AssessmentProvisioningRouteImport.update({
  id: '/provisioning',
  path: '/provisioning',
  getParentRoute: () => AssessmentRoute,
} as any)
const AssessmentCreateWorkspaceRoute =
  AssessmentCreateWorkspaceRouteImport.update({
    id: '/create-workspace',
    path: '/create-workspace',
    getParentRoute: () => AssessmentRoute,
  } as any)
const AssessmentConnectRoute = AssessmentConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AssessmentRoute,
} as any)
const AssessmentBusinessRoute = AssessmentBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AssessmentRoute,
} as any)
const AssessmentAnalysisRoute = AssessmentAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AssessmentRoute,
} as any)
const WorkspaceWorkflowReconciliationRoute =
  WorkspaceWorkflowReconciliationRouteImport.update({
    id: '/workflow/reconciliation',
    path: '/workflow/reconciliation',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRouteWithChildren
  '/system': typeof SystemRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/assessment/analysis': typeof AssessmentAnalysisRoute
  '/assessment/business': typeof AssessmentBusinessRoute
  '/assessment/connect': typeof AssessmentConnectRoute
  '/assessment/create-workspace': typeof AssessmentCreateWorkspaceRoute
  '/assessment/provisioning': typeof AssessmentProvisioningRoute
  '/assessment/recommendation': typeof AssessmentRecommendationRoute
  '/workspace/advisor': typeof WorkspaceAdvisorRoute
  '/workspace/connected': typeof WorkspaceConnectedRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/timeline': typeof WorkspaceTimelineRoute
  '/workspace/workflows': typeof WorkspaceWorkflowsRoute
  '/assessment/': typeof AssessmentIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/workflow/reconciliation': typeof WorkspaceWorkflowReconciliationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/system': typeof SystemRoute
  '/assessment/analysis': typeof AssessmentAnalysisRoute
  '/assessment/business': typeof AssessmentBusinessRoute
  '/assessment/connect': typeof AssessmentConnectRoute
  '/assessment/create-workspace': typeof AssessmentCreateWorkspaceRoute
  '/assessment/provisioning': typeof AssessmentProvisioningRoute
  '/assessment/recommendation': typeof AssessmentRecommendationRoute
  '/workspace/advisor': typeof WorkspaceAdvisorRoute
  '/workspace/connected': typeof WorkspaceConnectedRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/timeline': typeof WorkspaceTimelineRoute
  '/workspace/workflows': typeof WorkspaceWorkflowsRoute
  '/assessment': typeof AssessmentIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/workspace/workflow/reconciliation': typeof WorkspaceWorkflowReconciliationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRouteWithChildren
  '/system': typeof SystemRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/assessment/analysis': typeof AssessmentAnalysisRoute
  '/assessment/business': typeof AssessmentBusinessRoute
  '/assessment/connect': typeof AssessmentConnectRoute
  '/assessment/create-workspace': typeof AssessmentCreateWorkspaceRoute
  '/assessment/provisioning': typeof AssessmentProvisioningRoute
  '/assessment/recommendation': typeof AssessmentRecommendationRoute
  '/workspace/advisor': typeof WorkspaceAdvisorRoute
  '/workspace/connected': typeof WorkspaceConnectedRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/timeline': typeof WorkspaceTimelineRoute
  '/workspace/workflows': typeof WorkspaceWorkflowsRoute
  '/assessment/': typeof AssessmentIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/workflow/reconciliation': typeof WorkspaceWorkflowReconciliationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/system'
    | '/workspace'
    | '/assessment/analysis'
    | '/assessment/business'
    | '/assessment/connect'
    | '/assessment/create-workspace'
    | '/assessment/provisioning'
    | '/assessment/recommendation'
    | '/workspace/advisor'
    | '/workspace/connected'
    | '/workspace/settings'
    | '/workspace/timeline'
    | '/workspace/workflows'
    | '/assessment/'
    | '/workspace/'
    | '/workspace/workflow/reconciliation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/system'
    | '/assessment/analysis'
    | '/assessment/business'
    | '/assessment/connect'
    | '/assessment/create-workspace'
    | '/assessment/provisioning'
    | '/assessment/recommendation'
    | '/workspace/advisor'
    | '/workspace/connected'
    | '/workspace/settings'
    | '/workspace/timeline'
    | '/workspace/workflows'
    | '/assessment'
    | '/workspace'
    | '/workspace/workflow/reconciliation'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/system'
    | '/workspace'
    | '/assessment/analysis'
    | '/assessment/business'
    | '/assessment/connect'
    | '/assessment/create-workspace'
    | '/assessment/provisioning'
    | '/assessment/recommendation'
    | '/workspace/advisor'
    | '/workspace/connected'
    | '/workspace/settings'
    | '/workspace/timeline'
    | '/workspace/workflows'
    | '/assessment/'
    | '/workspace/'
    | '/workspace/workflow/reconciliation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRouteWithChildren
  SystemRoute: typeof SystemRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/assessment/': {
      id: '/assessment/'
      path: '/'
      fullPath: '/assessment/'
      preLoaderRoute: typeof AssessmentIndexRouteImport
      parentRoute: typeof AssessmentRoute
    }
    '/workspace/workflows': {
      id: '/workspace/workflows'
      path: '/workflows'
      fullPath: '/workspace/workflows'
      preLoaderRoute: typeof WorkspaceWorkflowsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/timeline': {
      id: '/workspace/timeline'
      path: '/timeline'
      fullPath: '/workspace/timeline'
      preLoaderRoute: typeof WorkspaceTimelineRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/settings': {
      id: '/workspace/settings'
      path: '/settings'
      fullPath: '/workspace/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/connected': {
      id: '/workspace/connected'
      path: '/connected'
      fullPath: '/workspace/connected'
      preLoaderRoute: typeof WorkspaceConnectedRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/advisor': {
      id: '/workspace/advisor'
      path: '/advisor'
      fullPath: '/workspace/advisor'
      preLoaderRoute: typeof WorkspaceAdvisorRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/assessment/recommendation': {
      id: '/assessment/recommendation'
      path: '/recommendation'
      fullPath: '/assessment/recommendation'
      preLoaderRoute: typeof AssessmentRecommendationRouteImport
      parentRoute: typeof AssessmentRoute
    }
    '/assessment/provisioning': {
      id: '/assessment/provisioning'
      path: '/provisioning'
      fullPath: '/assessment/provisioning'
      preLoaderRoute: typeof AssessmentProvisioningRouteImport
      parentRoute: typeof AssessmentRoute
    }
    '/assessment/create-workspace': {
      id: '/assessment/create-workspace'
      path: '/create-workspace'
      fullPath: '/assessment/create-workspace'
      preLoaderRoute: typeof AssessmentCreateWorkspaceRouteImport
      parentRoute: typeof AssessmentRoute
    }
    '/assessment/connect': {
      id: '/assessment/connect'
      path: '/connect'
      fullPath: '/assessment/connect'
      preLoaderRoute: typeof AssessmentConnectRouteImport
      parentRoute: typeof AssessmentRoute
    }
    '/assessment/business': {
      id: '/assessment/business'
      path: '/business'
      fullPath: '/assessment/business'
      preLoaderRoute: typeof AssessmentBusinessRouteImport
      parentRoute: typeof AssessmentRoute
    }
    '/assessment/analysis': {
      id: '/assessment/analysis'
      path: '/analysis'
      fullPath: '/assessment/analysis'
      preLoaderRoute: typeof AssessmentAnalysisRouteImport
      parentRoute: typeof AssessmentRoute
    }
    '/workspace/workflow/reconciliation': {
      id: '/workspace/workflow/reconciliation'
      path: '/workflow/reconciliation'
      fullPath: '/workspace/workflow/reconciliation'
      preLoaderRoute: typeof WorkspaceWorkflowReconciliationRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface AssessmentRouteChildren {
  AssessmentAnalysisRoute: typeof AssessmentAnalysisRoute
  AssessmentBusinessRoute: typeof AssessmentBusinessRoute
  AssessmentConnectRoute: typeof AssessmentConnectRoute
  AssessmentCreateWorkspaceRoute: typeof AssessmentCreateWorkspaceRoute
  AssessmentProvisioningRoute: typeof AssessmentProvisioningRoute
  AssessmentRecommendationRoute: typeof AssessmentRecommendationRoute
  AssessmentIndexRoute: typeof AssessmentIndexRoute
}

const AssessmentRouteChildren: AssessmentRouteChildren = {
  AssessmentAnalysisRoute: AssessmentAnalysisRoute,
  AssessmentBusinessRoute: AssessmentBusinessRoute,
  AssessmentConnectRoute: AssessmentConnectRoute,
  AssessmentCreateWorkspaceRoute: AssessmentCreateWorkspaceRoute,
  AssessmentProvisioningRoute: AssessmentProvisioningRoute,
  AssessmentRecommendationRoute: AssessmentRecommendationRoute,
  AssessmentIndexRoute: AssessmentIndexRoute,
}

const AssessmentRouteWithChildren = AssessmentRoute._addFileChildren(
  AssessmentRouteChildren,
)

interface WorkspaceRouteChildren {
  WorkspaceAdvisorRoute: typeof WorkspaceAdvisorRoute
  WorkspaceConnectedRoute: typeof WorkspaceConnectedRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceTimelineRoute: typeof WorkspaceTimelineRoute
  WorkspaceWorkflowsRoute: typeof WorkspaceWorkflowsRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceWorkflowReconciliationRoute: typeof WorkspaceWorkflowReconciliationRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceAdvisorRoute: WorkspaceAdvisorRoute,
  WorkspaceConnectedRoute: WorkspaceConnectedRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceTimelineRoute: WorkspaceTimelineRoute,
  WorkspaceWorkflowsRoute: WorkspaceWorkflowsRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceWorkflowReconciliationRoute: WorkspaceWorkflowReconciliationRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRouteWithChildren,
  SystemRoute: SystemRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
