/**
 * GST Utility Functions
 *
 * Single canonical source for all GST calculations across the Commercial OS.
 * Australian GST rate: 10%.
 *
 * IMPORTANT — two formulas exist:
 *
 *   GST-EXCLUSIVE (subtotal known, computing total):
 *     gstAmount = subtotal × 0.10
 *     total     = subtotal + gstAmount
 *   Used by: supplier onboarding when generating a draft invoice.
 *
 *   GST-INCLUSIVE (total known, extracting GST component):
 *     gstAmount = total ÷ 11
 *     subtotal  = total - gstAmount
 *   Used by: accounting export when receiving the GST-inclusive invoice total.
 *
 * Both formulas are arithmetically consistent — if an invoice has subtotal $1000:
 *   Exclusive: gst=$100, total=$1100
 *   Inclusive on $1100: gst=$1100/11=$100 ✓
 *
 * The bug occurs only when the fallback path in accounting-export applies the
 * inclusive formula to an obligation.amount that is GST-exclusive. This module
 * makes both paths explicit so callers cannot mix them.
 */

const GST_RATE = 0.10;
const GST_DIVISOR = 11; // 1 + 1/GST_RATE = 11 for 10% GST

/**
 * Compute the GST component when the INPUT is a GST-EXCLUSIVE subtotal.
 * i.e. the supplier has quoted a price before GST.
 * Returns null for non-GST-registered suppliers.
 */
export function calculateGstFromExclusiveSubtotal(
  subtotal: number,
  gstRegistered: boolean
): number | null {
  if (!gstRegistered) return null;
  return roundCurrency(subtotal * GST_RATE);
}

/**
 * Compute the GST component when the INPUT is a GST-INCLUSIVE total.
 * i.e. the invoice total already includes GST (as generated by supplier onboarding).
 * Returns 0 for non-GST-registered suppliers.
 */
export function calculateGstFromInclusiveTotal(
  totalInclusive: number,
  gstRegistered: boolean
): number {
  if (!gstRegistered) return 0;
  return roundCurrency(totalInclusive / GST_DIVISOR);
}

/**
 * Compute the GST-inclusive total from a GST-exclusive subtotal.
 * Used when building an invoice from obligation amounts.
 */
export function toGstInclusiveTotal(subtotal: number, gstRegistered: boolean): number {
  const gst = calculateGstFromExclusiveSubtotal(subtotal, gstRegistered) ?? 0;
  return roundCurrency(subtotal + gst);
}

/**
 * Compute the GST-exclusive subtotal from a GST-inclusive total.
 */
export function toGstExclusiveSubtotal(totalInclusive: number, gstRegistered: boolean): number {
  if (!gstRegistered) return totalInclusive;
  return roundCurrency(totalInclusive - calculateGstFromInclusiveTotal(totalInclusive, true));
}

function roundCurrency(value: number): number {
  return Math.round(value * 100) / 100;
}

/** The Australian GST rate constant, for documentation purposes. */
export const AUSTRALIAN_GST_RATE = GST_RATE;
